FROM python:3.10-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# only need the dash service file
COPY dash_service.py .  
COPY assets/ ./assets/

ENV DASH_PORT=8050
EXPOSE 8050

CMD ["python", "dash_service.py"]