name: Build & deploy Python container to Azure Web App

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  # ────────────────────────────────────────────────────────────────────────────
  # 1) Build & push container image
  # ────────────────────────────────────────────────────────────────────────────
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: "true"
          tags: docker.io/${{ secrets.DOCKERHUB_USER }}/poc-genie-web-app:${{ github.sha }}

  # ────────────────────────────────────────────────────────────────────────────
  # 2) Deploy that image to your existing App Service
  # ────────────────────────────────────────────────────────────────────────────
  deploy-container:
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: 'Deploy container to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'POC-genie-web-app'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB7A030785BB4A8DBFC44036C84F6519 }}
          images: >
            docker.io/${{ secrets.DOCKERHUB_USER }}/poc-genie-web-app:${{ github.sha }}
